version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs:3
    container_name: backend
    command: npm run start
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app

networks:
  default:
    name: backend_network
